version: "3.9"

services:
  schedulo:
    build: .
    container_name: schedulo
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"

      # Domain routing
      - "traefik.http.routers.schedulo.rule=Host(`schedule.pasbestventures.com`)"
      - "traefik.http.routers.schedulo.entrypoints=websecure"
      - "traefik.http.routers.schedulo.tls.certresolver=myresolver"

      # Service port (Nginx -> 80)
      - "traefik.http.services.schedulo.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
